### ISSUE TITLE
Upgrade plan 

### ISSUE THREAD

**Issue by Uio96** [ivapylibs/Surveillance#11]
### Phase One:

Information flow:

- [x] ROS publishers of the calibration data/camera intrinsics/bird-eye-view transformation matrix.
- [ ] ROS publishers of the transformations between the camera, workspace, and the robot (mainly for robot, cannot be obtained from current recorded data).
- [ ] ROS publishers of the layers' information: segmentation results and the tracker states (More postprocessing results).

Rosbag-based Calibration:

- [x] The system builder from the rosbag.

Rosbag recorder(raw RGB-D data)/runner(reading & layered-approach processing) scripts:

- [x] Add the automatic start for roscore to the ros deployment scripts.
- [x] (Dependent on the rosbag-based calibration item above) Build from the calibration data in the pre-saved rosbag file, and run on the test data stored in that same rosbag file. i.e. **The runner**.
- [x] (Dependent on the rosbag-based calibration item above) Build from the pre-saved calibration data, and record both the calibration information and the test data into a new rosbag. 
- [x] README for the usage of the rosbag recorder and runner.
- [x] Add more options to the interaction part, e.g., record keypoard.
- [x] Fix the missing frame issue in the runner.
 
Miscellaneous:
- [x] Update the hints in the process (more user-friendly).
- [ ] Update the installation libraries by git submodule.
- [ ] A detailed plot of the system design for further development (including connection of Surveillance/camera/ROS wrapper).
- [x] Incorporate the postprocessing functions from puzzle_data_collector (may move them to the puzzle solver).

### Phase Two:

ROS package (Will be implemented in the [Mary_ROS](https://github.gatech.edu/VisMan/Mary_ROS) package.)- Build a package for the Surveillance. Establish different launch files for different functionalities, including:

- [x] Deployment:
  - [x] Build from the presaved rosbag file and deploy.
  - [ ] Build from the camera source, record the calibration data into the rosbag, and deploy.

**Comment by pv33** [comment]
Plan no longer relevant.  Closing.
